version: '3.8'

services:
  scraper:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./src:/app
    command: python /app/main.py

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
